### PR TITLE
Fix #143: When LAN access is denied from everyone, UI is unclear

### LINKED ISSUE #143: When LAN access is denied from everyone, UI is unclear
Instead of showing language selection, user should be prompted to press the configuration button if all LAN access is denied.
image

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Comment by ojousima** [comment]
If possible, the language selection dialog should be hidden

**Comment by TheSomeMan** [comment]
> If possible, the language selection dialog should be hidden

then the message will be displayed only in English, is it ok?

**Comment by ojousima** [comment]
Let's keep the language selection after all, I didn't realize it would change the message language too

**Review by ojousima — APPROVED** [review]
Thanks

**Pull request merged**
