### PR TITLE
#178: Request new configuration remotely

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Review by ojousima — APPROVED** [review]
Thanks

**Comment by TheSomeMan** [comment]
image

@ojousima I have a question, maybe it's better to hide the token (for bearer authentication) when configuration is downloaded from the gateway (as we do for passwords)?

**Comment by ojousima** [comment]
@TheSomeMan If I'm understanding correctly, showing the bearer token could result in attacker opening the configuration interface and read the downloaded bearer token? If yes, the bearer token should be hidden for security.

**Review by ojousima — APPROVED** [review]
Thanks

**Pull request merged**
